name: Python CI

on:
  push:
  pull_request:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.12"

      - name: Run Python file
        run: python main.py
